apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "namespace-manager.fullname" . }}
  labels:
    {{- include "namespace-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "namespace-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "namespace-manager.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "namespace-manager.serviceAccountName" . }}
      containers:
      - name: namespace-manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}