{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "namespace-manager.serviceAccountName" . }}
  labels:
    {{- include "namespace-manager.labels" . | nindent 4 }}
{{- end }}